### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MarcTheDev** [DeedleFake/ptt-fix#1]
First off this works and I was looking for a while, but do you have an example of using mouse button 9 (the mouse button) ? I am not sure how to do this and I saw you mentioned it on the bottom but I am new to these keycodes.

**Comment by DeedleFake** [comment]
There isn't support for mouse input at the moment. I can add it, though.

**Comment by MarcTheDev** [comment]
> There isn't support for mouse input at the moment. I can add it, though.

I was able to fix this by setting my mouse button to F9 using piper, now im stuck on trying to make the program into a service. Do you by chance know how, so we would not have to manually run it in terminal.

**Comment by DeedleFake** [comment]
Edit: I was partially wrong about being wrong. ptt-fix could listen for mouse input, but it couldn't output mouse buttons for Discord to see. I have now implemented support for that. To output a mouse button, use `-sym mouse:<number>`. In other words, to output mouse 2, use `-sym mouse:2`.

I was apparently wrong. I thought the input worked differently than it does but there _is_ already support for the mouse. For example, to listen for left-clicks and output the same to Discord, you can use

```bash
$ ptt-fix -key 0x110 -sym Pointer_Left
```

> I was able to fix this by setting my mouse button to F9 using piper, now im stuck on trying to make the program into a service. Do you by chance know how, so we would not have to manually run it in terminal.

I use my own systemd user service unit. I can add one as an example, but because the config for the program is done as command-line arguments, the unit file will have to be edited to change them. If you don't use systemd, I'm afraid that I can't help as much.

**Comment by MarcTheDev** [comment]
> I was apparently wrong. I thought the input worked differently than it does but there _is_ already support for the mouse. For example, to listen for left-clicks and output the same to Discord, you can use
> 
> ```shell
> $ ptt-fix -key 0x110 -sym Pointer_Left
> ```
> 
> > I was able to fix this by setting my mouse button to F9 using piper, now im stuck on trying to make the program into a service. Do you by chance know how, so we would not have to manually run it in terminal.
> 
> I use my own systemd user service unit. I can add one as an example, but because the config for the program is done as command-line arguments, the unit file will have to be edited to change them. If you don't use systemd, I'm afraid that I can't help as much.

Yeah I use systemd. If you can add an example I am sure I can work around it.

**Comment by DeedleFake** [comment]
I added one to the README. I'm going to go ahead and close this. Please feel free to reopen it and let me know if you have any questions or need anything clarified.
